# Generated by Django 5.0.4 on 2024-05-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval_app', '0003_pereval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='status',
            field=models.CharField(default='new', max_length=10),
        ),
    ]
